version: '3.3'

services:
  db:
    image: mysql/mysql-server:8.0
    restart: always
    environment:
      MYSQL_DATABASE: 'testdb'
      MYSQL_ROOT_PASSWORD: 'test'
      MYSQL_ROOT_HOST: '%'
    ports:
      - "3307:3307"
    volumes:
      - db-data:/var/lib/mysql

  web:
    build: ./web 
    ports:
      - "80:80"
    depends_on:
      - db
    environment:
      DATABASE_HOST: db

volumes:
  db-data:
